CREATE ROLE IF NOT EXISTS REPORTER;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE REPORTER;
GRANT USAGE ON DATABASE spotify_db TO ROLE REPORTER;
GRANT USAGE ON SCHEMA spotify_schema TO ROLE REPORTER;

GRANT SELECT ON ALL TABLES IN SCHEMA spotify_schema TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA spotify_schema TO ROLE REPORTER;

GRANT ROLE REPORTER TO USER DA_USER;
GRANT ROLE REPORTER TO USER "phong le";
SHOW users

USE ROLE USERADMIN; 
DROP USER DA_USER
CREATE USER DA_USER 
    PASSWORD = 'password'
    LOGIN_NAME = 'DA_USER' 
    DEFAULT_ROLE = REPORTER 
    MUST_CHANGE_PASSWORD = FALSE; 
GRANT ROLE REPORTER TO USER DA_USER;